version: "3.7"

services:
  postgis:
    image: postgis/postgis:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=mygisdb
    volumes:
      - ./data:/var/lib/postgresql/data